name: ExAFK
version: 1.1.1
author: Jackerugo
description: Displays titles and/or effects to players that are AFK.
main: me.exafk.Main
website: https://github.com/Jackerugo/ExAFK/issues
depend: [Essentials]
softdepend: [PlaceholderAPI]
commands:
  exafk:
    description: Base command for ExAFK.
